"""Edit defence stucture

Revision ID: c0e5785bbdff
Revises: 170ad6790cf2
Create Date: 2022-01-24 19:10:36.558345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e5785bbdff'
down_revision = '170ad6790cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('secret_value_under', sa.Integer(), nullable=True))
    op.add_column('content', sa.Column('secret_value_top', sa.Integer(), nullable=True))
    op.add_column('tokens', sa.Column('game', sa.Integer(), nullable=True))
    op.add_column('tokens', sa.Column('sequence_seed', sa.Integer(), nullable=True))
    op.add_column('tokens', sa.Column('secret_key', sa.Integer(), nullable=True))
    op.add_column('tokens', sa.Column('sequence_member', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tokens', 'content', ['game'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_column('tokens', 'sequence_member')
    op.drop_column('tokens', 'secret_key')
    op.drop_column('tokens', 'sequence_seed')
    op.drop_column('tokens', 'game')
    op.drop_column('content', 'secret_value_top')
    op.drop_column('content', 'secret_value_under')
    # ### end Alembic commands ###
