"""Donwload data for games

Revision ID: dbd7c9b4886e
Revises: 
Create Date: 2022-09-14 14:32:13.752389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd7c9b4886e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('donwloads', sa.Integer(), nullable=True, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'donwloads')
    # ### end Alembic commands ###
